name: Publish and Test

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      role:
        required: true
        type: string
      public_repository:
        required: true
        type: string
      private_repository:
        required: true
        type: string
      chart_branch:
        required: true
        type: string
      charts_url:
        required: true
        type: string

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    uses: './.github/workflows/on-release.yml'
    with:
      version: ${{ inputs.version }}
      role: ${{ inputs.role }}
      public_repository: ${{ inputs.public_repository }}
      private_repository: ${{ inputs.private_repository }}
      chart_branch: ${{ inputs.chart_branch }}
      charts_url: ${{ inputs.charts_url }}
    secrets: inherit

  e2e:
    needs: publish
    strategy:
      fail-fast: false
      matrix:
        architecture: [ arm64, x86_64 ]
    permissions:
      id-token: write
      contents: read
    uses: './.github/workflows/on-safe-to-test-label.yml'
    with:
      architecture: ${{ matrix.architecture }}
      chart_repository: ${{ inputs.charts_url }}
      chart_version: ${{ inputs.version }}
      image_repository: ${{ inputs.public_repository }}

  check-latest:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      VERSION: ${{ inputs.version }}
      PUBLIC_REPOSITORY: ${{ inputs.public_repository }}
      PRIVATE_REPOSITORY: ${{ inputs.private_repository }}
    steps:
    - name: Check out code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: us-east-1
    - name: Login to Public ECR
      uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
      with:
        registry-type: public
    - name: Login to Private ECR
      uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
    - name: Check latest points at this version
      run: |
        hack/check-latest.sh "$PUBLIC_REPOSITORY" "$VERSION"
        hack/check-latest.sh "$PRIVATE_REPOSITORY" "$VERSION"
